accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

geoapp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('mapviewer.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

mapviewer/urls.py
from django.urls import path
from mapviewer import views

urlpatterns = [
    path('', views.listado_yacimientos, name='listado_yacimientos'),
#     path('mapa/', views.mapa_yacimientos, name='mapa_Yacimientoes'),
    path('yacimiento/<int:pk>/', views.detalle_yacimiento, name='detalle_yacimiento'),
    path('yacimiento/nuevo/', views.nuevo_yacimiento, name='nuevo_yacimiento'),     
    path('yacimiento/<int:pk>/editar/', views.editar_yacimiento, name='editar_yacimiento'),
    path('yacimiento/buscador/', views.buscador_yacimientos, name='buscador_yacimientos'),
    path('ajax/opciones-provincia/', views.opciones_provincia, name='opciones_provincia'),
    path('ajax/opciones-municipio/', views.opciones_municipio, name='opciones_municipio'), 
]

accounts/models.py
from django.db import models

# Create your models here.

mapviewer/models.py
from django.db import models
from django.contrib.gis.db import models as gis_models

# Create your models here.
class ComunidadAutonoma(models.Model):
    nombre = models.CharField(max_length=100)
    def __str__(self):
        return self.nombre

class Provincia(models.Model):
    nombre = models.CharField(max_length=100)
    comunidad_autonoma = models.ForeignKey(ComunidadAutonoma, on_delete=models.SET_NULL, null=True)
    def __str__(self):
        return self.nombre
    
class Municipio(models.Model):
    nombre = models.CharField(max_length=100)
    provincia = models.ForeignKey(Provincia, on_delete=models.SET_NULL, null=True)
    def __str__(self):
        return self.nombre
    
class TipoYacimiento(models.Model):
    nombre = models.CharField(max_length=100)
    def __str__(self):
        return self.nombre
    
class TipoFaseHistorica(models.Model):
    nombre = models.CharField(max_length=100)
    def __str__(self):
        return self.nombre

class Yacimiento(models.Model):
    usuario = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    nombre = models.CharField(max_length=200)
    localizacion = gis_models.PolygonField()
    municipio = models.ForeignKey(Municipio, on_delete=models.SET_NULL, null=True)
    provincia = models.ForeignKey(Provincia, on_delete=models.SET_NULL, null=True)
    comunidad_autonoma = models.ForeignKey(ComunidadAutonoma, on_delete=models.SET_NULL, null=True)
    tipo = models.ForeignKey(TipoYacimiento, on_delete=models.SET_NULL, null=True)
    fase_historica = models.ForeignKey(TipoFaseHistorica, on_delete=models.SET_NULL, null=True)
    #cronologia
    #intervenciones
    #bibliografia
    observaciones = models.TextField()
    
    def __str__(self):
        return self.nombre
    

mapviewer/forms.py
from django.contrib.gis import forms
from django.utils.translation import ugettext_lazy
from .models import Yacimiento, Provincia, Municipio

class YacimientoForm(forms.ModelForm):
    class Meta:
        model = Yacimiento
        fields = ('nombre', 'localizacion', 'comunidad_autonoma', 'provincia', 'municipio', 'tipo', 'fase_historica', 'observaciones')
        labels = {
            'nombre' : ugettext_lazy('Nombre'),
            'localizacion' : ugettext_lazy('Localización'),
            'comunidad_autonoma' : ugettext_lazy('Comunidad autónoma'),
            'provincia' : ugettext_lazy('Provincia'),
            'municipio' : ugettext_lazy('Municipio'),
            'tipo' : ugettext_lazy('Tipo de yacimiento'),
            'fase_historica' : ugettext_lazy('Fase histórica'),
            'observaciones' : ugettext_lazy('Observaciones'),
        }
        widgets = {
            'localizacion' : forms.OSMWidget(attrs={
                'default_lat' : 40.4378698,
                'default_lon' : -3.8196207,
                'default_zoom' : 5,
            }),
        }
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        if self.instance.pk:
            self.fields['provincia'].queryset = self.instance.comunidad_autonoma.provincia_set.order_by('nombre')
            self.fields['municipio'].queryset = self.instance.provincia.municipio_set.order_by('nombre')
        else:
            self.fields['provincia'].queryset = Provincia.objects.none()
            self.fields['municipio'].queryset = Municipio.objects.none()
            if 'comunidad_autonoma' in self.data:
                try:
                    comunidad_autonoma_id = int(self.data.get('comunidad_autonoma'))
                    self.fields['provincia'].queryset = Provincia.objects.filter(comunidad_autonoma_id=comunidad_autonoma_id).order_by('nombre')
                except (ValueError, TypeError):
                    pass  # invalid input from the client; ignore and fallback to empty
            if 'provincia' in self.data:
                try:
                    provincia_id = int(self.data.get('provincia'))
                    self.fields['municipio'].queryset = Municipio.objects.filter(provincia_id=provincia_id).order_by('nombre')
                except (ValueError, TypeError):
                    pass  # invalid input from the client; ignore and fallback to empty
            
        

accounts/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.urls.base import reverse_lazy

# Create your views here.
class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

mapviewer/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from .models import Yacimiento, Provincia, Municipio
from .forms import YacimientoForm
from mapviewer.models import TipoYacimiento, TipoFaseHistorica

# Create your views here.

def listado_yacimientos(request):
    yacimientos = Yacimiento.objects.all()
    return render(request, 'mapviewer/listado_yacimientos.html', {'yacimientos' : yacimientos})

def detalle_yacimiento(request, pk):
    yacimiento = get_object_or_404(Yacimiento.objects.all(), pk=pk)
    return render(request, 'mapviewer/detalle_yacimiento.html', {'yacimiento' : yacimiento})

@login_required
def nuevo_yacimiento(request):
    if request.method == 'POST':
        form = YacimientoForm(request.POST)
        if form.is_valid():
            yacimiento = form.save(commit=False)
            yacimiento.usuario = request.user
            yacimiento.save()
            return redirect('detalle_yacimiento', pk=yacimiento.pk)
    else:
        form = YacimientoForm()
    return render(request, 'mapviewer/editar_yacimiento.html', {'form': form})

@login_required
def editar_yacimiento(request, pk):
    yacimiento = get_object_or_404(Yacimiento, pk=pk)
    if request.method == 'POST':
        form = YacimientoForm(request.POST, instance=yacimiento)
        if form.is_valid():
            yacimiento = form.save(commit=False)
            yacimiento.usuario = request.user
            yacimiento.save()
            return redirect('detalle_yacimiento', pk=yacimiento.pk)
    else:
        form = YacimientoForm(instance=yacimiento)
    return render(request, 'mapviewer/editar_yacimiento.html', {'form': form})

def buscador_yacimientos(request):
    tipos_yacimiento = TipoYacimiento.objects.all()
    tipos_fase_historica = TipoFaseHistorica.objects.all()
    return render(request,
                  'mapviewer/buscador_yacimientos.html',
                  {                   
                      'tipos_yacimento' : tipos_yacimiento,
                      'tipos_fase_historica' : tipos_fase_historica,
                  })


def opciones_provincia(request):
    comunidad_autonoma_id = request.GET.get('comunidad-autonoma-id')
    if comunidad_autonoma_id == '':
        provincias = Provincia.objects.none()
    else:
        provincias = Provincia.objects.filter(comunidad_autonoma_id=comunidad_autonoma_id).order_by('nombre')
    return render(request, 'mapviewer/dropdown_options.html', {'options': provincias})

def opciones_municipio(request):
    provincia_id = request.GET.get('provincia-id')
    if provincia_id == '':
        municipios = Municipio.objects.none()
    else:
        municipios = Municipio.objects.filter(provincia_id=provincia_id).order_by('nombre')
    return render(request, 'mapviewer/dropdown_options.html', {'options': municipios})
    

mapviewer/templates/mapviewer/base.html
{% load static i18n %}
<html>
<head>
<title>GeoApp Django</title>
<link rel="stylesheet"
	href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
<script
	src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script
	src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script
	src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
<link rel="stylesheet"
	href="https://fonts.googleapis.com/css?family=Knewave">
<link rel="stylesheet"
	href="https://use.fontawesome.com/releases/v5.1.1/css/all.css">
<link rel="stylesheet" type="text/css"
	href="{% static 'css/style.css' %}">
</head>
<body>
	<div class="app-header">
		<h1 class="p-3">
			<a href="/">{% trans "Proyecto Rusko" %}</a>
		</h1>
		<nav class="app-menu navbar navbar-expand-lg navbar-dark bg-dark">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item">
					<div class="nav-item dropdown dropdown-dark">
						<button class="btn btn-secondary dropdown-toggle" id="navbarDropdown" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							<i class="fas fa-university"></i>{% trans "Yacimientos" %}
						</button>
						<div class="dropdown-menu bg-dark text-light" aria-labelledby="navbarDropdown">						
							<a class="dropdown-item" href="/yacimiento/buscador"><i class="fas fa-search"></i>{% trans "Buscador" %}</a>
							<a class="dropdown-item" href="/"><i class="fas fa-atlas"></i>{% trans "Listado" %}</a>
		   					<a class="dropdown-item" href="/yacimiento/nuevo"><i class="fas fa-map-marked-alt"></i>{% trans "Crear yacimiento" %}</a>
						</div>
					</div>	
				</li>
			</ul>
			{% if user.is_authenticated %}		
				<div class="nav-item dropdown">
					<button class="btn btn-secondary dropdown-toggle" id="navbarDropdown" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<i class="fas fa-user"></i>{{ user.username }}
					</button>
					<div class="dropdown-menu dropdown-menu-right bg-dark text-light" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="#"><i class="fas fa-edit"></i>{% trans "Editar perfil" %}</a>
	   					<div class="dropdown-divider"></div>					
						<a class="dropdown-item" href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i>{% trans "Cerrar sesión" %}</a>
					</div>
				</div>			
			{% else %}
				<div class="nav-item">
					<a class="btn btn-secondary" href="{% url 'login' %}"><i class="fas fa-sign-in-alt"></i>{% trans "Iniciar sesión" %}</a>
				</div>
			{% endif %}
		</nav>
	</div>
	<div class="d-flex">
		<div id="app-content" class="container">
			{% block content %}
			{% endblock %}
		</div>
	</div>
</body>
</html>

mapviewer/templates/mapviewer/buscador_yacimientos.html
{% extends 'mapviewer/base.html' %}
{% load i18n %}


{% block content %}
	<div class="buscador-yacimientos d-flex">
		<nav id="buscador-sidebar">
			<h3>{% trans "Filtros de búsqueda" %}</h3>
			<ul class="list-unstyled">
				<li>
					<span>{% trans "Nombre" %}:</span>
					<input type="text" id="filtro_nombre" />
				</li>
				<li>
					<a data-toggle="collapse" href="#lista-tipos-yacimiento" role="button" aria-expanded="true" class="dropdown-toggle">
				    	{% trans "Tipo de yacimiento" %} 
					</a>
					<ul class="collapse show list-unstyled" id="lista-tipos-yacimiento">
						{% for tipo_yacimento in tipos_yacimento %}
							<li>
								<input type="checkbox" id="tipo-yacimiento-{{ tipo_yacimento.pk }}" name="tipo-yacimiento[]" value="{{ tipo_yacimento.pk }}" />
								<label for="tipo-yacimiento-{{ tipo_yacimento.pk }}">{{ tipo_yacimento.nombre }}</label>
							</li>
						{% endfor %}
					</ul>
				</li>
				<li>
					<a data-toggle="collapse" href="#lista-tipos-fase-historica" role="button" aria-expanded="true" class="dropdown-toggle">
				    	{% trans "Fase histórica" %} 
					</a>
					<ul class="collapse show list-unstyled" id="lista-tipos-fase-historica">
						{% for tipo_fase_historica in tipos_fase_historica %}
							<li>
								<input type="checkbox" id="tipo-fase-historica-{{ tipo_fase_historica.pk }}" name="tipo-fase-historica[]" value="{{ tipo_fase_historica.pk }}" />
								<label for="tipo-fase-historica-{{ tipo_fase_historica.pk }}">{{ tipo_fase_historica.nombre }}</label>
							</li>
						{% endfor %}
					</ul>
				</li>
				<li>
					<button type="button" class="btn btn-primary mx-auto">{% trans "Buscar" %}</button>
				</li>
			</ul>
		</nav>
		<div id="buscador-resultados" class="flex-grow-1">
			<h2>{% trans "Buscador de yacimientos" %}</h2>
			<div id="map" class="map"></div>
		</div>
	</div>
	<script
		src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
	<script
		src="https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.1.3/build/ol.js"></script>
	<script>
		var vectorSource = new ol.source.Vector();
		vectorSource.on('change', function(evt){
			if (vectorSource.getState() === 'ready') {
				if (vectorSource.getFeatures().length > 0) {
					map.getView().fit(vectorSource.getExtent(), map.getSize());
				}
			}
		});
		var styleFunction = function(feature) {
			if (feature.getGeometry().getType() == 'Polygon') {
				return new ol.style.Style({
					stroke :  new ol.style.Stroke({
						color : 'darkgreen',
						width : 2
					}),
					fill : new ol.style.Fill({
						color : [0, 200, 0, 0.4]
					}),
				});
			} else if (feature.getGeometry().getType() == 'Point') {
				return new ol.style.Style({
					image: new ol.style.Circle(/** @type {olx.style.IconOptions} */ ({
		 				stroke : new ol.style.Stroke({
		 					color : 'darkred'
		 				}),	
		 				fill : new ol.style.Fill({
		 					color : 'red'
		 				}),
		 				radius : 4,
		 			}))
				});
			}
		};
		var map = new ol.Map({
			target : 'map',
			layers : [
				new ol.layer.Tile({
					source : new ol.source.OSM()
				}),
				new ol.layer.Vector({
					source: vectorSource,
					style: styleFunction
				}),
			],
			view: new ol.View({
				center: ol.proj.transform([-3.8196207, 36.4378698], 'EPSG:4326', 'EPSG:3857'),
		        zoom: 5,
		    })
		});
	</script>
{% endblock %}

mapviewer/templates/mapviewer/detalle_yacimiento.html
{% extends 'mapviewer/base.html' %}
{% load i18n %}
{% load l10n %}

{% block content %}
	<div class="yacimiento">
		<div class="d-flex yacimiento-header">
			<h3 class="p-2 mr-auto">{{ yacimiento.nombre }}</h3>
			<div class="p-2 opciones">
				{% if user == yacimiento.usuario %}
					<a role="button" href="{% url 'editar_yacimiento' pk=yacimiento.pk %}" class="btn btn-primary">
						<i class="fas fa-pencil-alt"></i>
					</a>
				{% endif %}
			</div>
		</div>
		<p class="subtitulo">{% trans "Creado por" %}: {{ yacimiento.usuario }}</p>
		<div class="container yacimiento-details">
			<div id="map" class="row map"></div>
			<div class="row">
				<span class="col-md-2 nombre-campo">{% trans "Comunidad Autónoma" %}:</span>
				<span class="col-md">{{ yacimiento.comunidad_autonoma.nombre }}</span>
			</div>
			<div class="row">
				<span class="col-md-2 nombre-campo">{% trans "Provincia" %}:</span>
				<span class="col-md">{{ yacimiento.provincia.nombre }}</span>
			</div>
			<div class="row">
				<span class="col-md-2 nombre-campo">{% trans "Municipio" %}:</span>
				<span class="col-md">{{ yacimiento.municipio.nombre }}</span>
			</div>
			<div class="row">
				<span class="col-md-2 nombre-campo">{% trans "Observaciones" %}:</span>
				<span class="col-md">{{ yacimiento.observaciones }}</span>
			</div>			
		</div>
	</div>
	<script
		src="https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.1.3/build/ol.js"></script>
	<script type="text/javascript">
		var vectorSource = new ol.source.Vector();
		vectorSource.on('change', function(evt){
			if (vectorSource.getState() === 'ready') {
				if (vectorSource.getFeatures().length > 0) {
					map.getView().fit(vectorSource.getExtent(), map.getSize());
				}
			}
		});
		var styleFunction = function(feature) {
			if (feature.getGeometry().getType() == 'Polygon') {
				return new ol.style.Style({
					stroke :  new ol.style.Stroke({
						color : 'darkgreen',
						width : 2
					}),
					fill : new ol.style.Fill({
						color : [0, 200, 0, 0.4]
					}),
				});
			} else if (feature.getGeometry().getType() == 'Point') {
				return new ol.style.Style({
					image: new ol.style.Circle(/** @type {olx.style.IconOptions} */ ({
		 				stroke : new ol.style.Stroke({
		 					color : 'darkred'
		 				}),	
		 				fill : new ol.style.Fill({
		 					color : 'red'
		 				}),
		 				radius : 4,
		 			}))
				});
			}
		};
		var map = new ol.Map({
			target : 'map',
			layers : [
				new ol.layer.Tile({
					source : new ol.source.OSM()
				}),
				new ol.layer.Vector({
					source: vectorSource,
					style: styleFunction
				}),
			],
			view: new ol.View({
				center: [0, 0],
		        zoom: 1
		    })
		});
		vectorSource.addFeatures(
			(new ol.format.GeoJSON()).readFeatures({{ yacimiento.localizacion.geojson|safe }}, {
			dataProjection: 'EPSG:4326',
			featureProjection: 'EPSG:3857'
			})
		);
	</script>
{% endblock %}

mapviewer/templates/mapviewer/dropdown_options.html
<option value="">---------</option>
{% for option in options %}
<option value="{{ option.pk }}">{{ option.nombre }}</option>
{% endfor %}

mapviewer/templates/mapviewer/editar_yacimiento.html
{% extends 'mapviewer/base.html' %}
{% load i18n %}

{% block content %}
	{{ form.media }}
	<h2>{% trans "Editar yacimiento" %}</h2>
	<form method="POST" class="yacimiento-form">{% csrf_token %}
		<table>
			{{ form.as_table }}
		</table>
		<button type="submit" class="btn btn btn-outline-success btn-guardar">{% trans "Guardar" %}</button>
	</form>
	<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
	<script>
		$("#id_comunidad_autonoma").change(function () {
			var comunidadAutonomaId = $(this).val(); 
			$.when(
				$.ajax({                      
					url: '{% url 'opciones_provincia' %}',                    
					data: {
						'comunidad-autonoma-id': comunidadAutonomaId       
					},
				}),
				$.ajax({                      
					url: '{% url 'opciones_municipio' %}',                    
					data: {
						'provincia-id': ''       
					},
				})
			)
			.done(function(optionsProvincia, optionsMunicipio) {
				$("#id_provincia").html(optionsProvincia);
				$("#id_municipio").html(optionsMunicipio);
			});
		});
		$("#id_provincia").change(function () {
			var url = '{% url 'opciones_municipio' %}';
			var provinciaId = $(this).val(); 
			$.ajax({                      
				url: '{% url 'opciones_municipio' %}',                    
				data: {
					'provincia-id': provinciaId       
				},
			})
			.done(function(optionsMunicipio) {
				$("#id_municipio").html(optionsMunicipio);
			});		
		});
	</script>
{% endblock %}

mapviewer/templates/mapviewer/listado_yacimientos.html
{% extends 'mapviewer/base.html' %}
{% load i18n %}

{% block content %}
	<div class="listado">
		{% for yacimiento in yacimientos %}
		<div class="yacimiento">
			<h4>
				<a href="{% url 'detalle_yacimiento' pk=yacimiento.pk %}">
					<i class="fas fa-map-marker-alt"></i>
					{{ yacimiento.nombre }}
				</a>					
			</h4>
			<div class="subtitulo">{% trans "Creado por" %}: {{ yacimiento.usuario }}</div>
		</div>
		{% endfor %}
	</div>
{% endblock %}